// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhfiawskggxnvffcpaxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoZmlhd3NrZ2d4bnZmZmNwYXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5OTg0NzAsImV4cCI6MjA2ODU3NDQ3MH0.tyZ7lU3EDYCWrTXb-4uA_kkb38fDlvzYP7bp8JapZFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});